import {
  LayoutDashboard,
  Users,
  BookOpen,
  Image as ImageIcon,
  ShieldAlert,
  CreditCard,
  ShieldCheck,
} from "lucide-react";

export const stats = [
  { title: "Total Users", value: "1,284", change: "+12%", icon: Users },
  { title: "Stories Created", value: "8,942", change: "+18%", icon: BookOpen },
  { title: "Images Generated", value: "15,637", change: "+9%", icon: ImageIcon },
  { title: "API Errors", value: "23", change: "-6%", icon: ShieldAlert },
];

export const users = [
  {
    id: 1,
    name: "Lina Ahmad",
    email: "lina@example.com",
    role: "Parent",
    plan: "Premium",
    stories: 14,
    images: 31,
    totalSpent: "$48",
    joinedAt: "Apr 03, 2026",
    status: "Active",
    lastActive: "2h ago",
  },
  {
    id: 2,
    name: "Omar Naser",
    email: "omar@example.com",
    role: "Parent",
    plan: "Free",
    stories: 7,
    images: 12,
    totalSpent: "$0",
    joinedAt: "Mar 28, 2026",
    status: "Banned",
    lastActive: "1d ago",
  },
  {
    id: 3,
    name: "Sara Ali",
    email: "sara@example.com",
    role: "Teacher",
    plan: "Premium",
    stories: 22,
    images: 45,
    totalSpent: "$96",
    joinedAt: "Feb 15, 2026",
    status: "Active",
    lastActive: "12m ago",
  },
  {
    id: 4,
    name: "Nour Sami",
    email: "nour@example.com",
    role: "Parent",
    plan: "Premium",
    stories: 9,
    images: 18,
    totalSpent: "$12",
    joinedAt: "Apr 11, 2026",
    status: "Suspended",
    lastActive: "3d ago",
  },
];

export const stories = [
  { id: 1, title: "The Brave Little Cloud", genre: "Fantasy", author: "Lina Ahmad", createdAt: "Apr 19, 2026", status: "Published" },
  { id: 2, title: "Milo Learns Kindness", genre: "Educational", author: "Sara Ali", createdAt: "Apr 18, 2026", status: "Draft" },
  { id: 3, title: "The Golden Forest", genre: "Adventure", author: "Omar Naser", createdAt: "Apr 17, 2026", status: "Published" },
];

export const images = [
  {
    id: 1,
    story: "The Brave Little Cloud",
    user: "Lina Ahmad",
    prompt: "A smiling cloud carrying a lantern over a moonlit village, watercolor style",
    model: "Leonardo Vision",
    size: "1024x1024",
    credits: 8,
    createdAt: "Apr 22, 2026",
    moderation: "Safe",
    status: "Approved",
  },
  {
    id: 2,
    story: "Milo Learns Kindness",
    user: "Sara Ali",
    prompt: "A gentle classroom scene where Milo shares toys with friends, soft pastel illustration",
    model: "Gemini Image",
    size: "1024x1024",
    credits: 6,
    createdAt: "Apr 22, 2026",
    moderation: "Review",
    status: "Pending",
  },
  {
    id: 3,
    story: "The Golden Forest",
    user: "Omar Naser",
    prompt: "A glowing enchanted forest with golden leaves and a curious child explorer",
    model: "Leonardo Vision",
    size: "1536x1024",
    credits: 10,
    createdAt: "Apr 21, 2026",
    moderation: "Flagged",
    status: "Rejected",
  },
  {
    id: 4,
    story: "Luna and the Moon",
    user: "Nour Sami",
    prompt: "A little girl floating through the stars beside a smiling moon, dreamy storybook art",
    model: "Gemini Image",
    size: "1024x1024",
    credits: 7,
    createdAt: "Apr 20, 2026",
    moderation: "Safe",
    status: "Approved",
  },
  {
    id: 5,
    story: "The Singing River",
    user: "Yousef Kareem",
    prompt: "A magical river made of musical notes winding through a bright green valley",
    model: "Leonardo Vision",
    size: "1024x1536",
    credits: 9,
    createdAt: "Apr 19, 2026",
    moderation: "Review",
    status: "Pending",
  },
];

export const logs = [
  { id: 1, type: "429", source: "Gemini API", detail: "Quota exceeded during generateContent request", time: "10 min ago" },
  { id: 2, type: "403", source: "Gemini API", detail: "Project denied access to model", time: "42 min ago" },
  { id: 3, type: "Timeout", source: "Leonardo API", detail: "Image generation polling exceeded max attempts", time: "1h ago" },
  { id: 4, type: "500", source: "Story Service", detail: "Unexpected JSON parse structure", time: "3h ago" },
];

export const navItems = [
  { key: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { key: "admins", label: "Admins", icon: ShieldCheck },
  { key: "users", label: "Users", icon: Users },
  { key: "stories", label: "Stories", icon: BookOpen },
  { key: "images", label: "Images", icon: ImageIcon },
  { key: "logs", label: "Logs", icon: ShieldAlert },
  { key: "payments", label: "Payments", icon: CreditCard },
];
